"""
Pydantic models for Characters (Batch generation feature).

A Character is a real row in the product `characters` table (the one the chat
app reads): a persona stored in flat typed columns, attached to a single "hero"
photo (profile/avatar/chat_avatar URLs). Batches are generated by editing that
hero photo, so identity stays consistent across the whole set.

Characters are created with status='draft'; the admin publishes them from the
existing admin UI once the generated photos look right.
"""
from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field, field_validator

from services.url_guard import validate_source_image, SourceImageError

from .requests import PersonaOptions


class CharacterCreate(BaseModel):
    """Request body for POST /v1/characters."""

    persona: PersonaOptions = Field(..., description="Character persona (identity + traits)")
    hero_image_url: str = Field(
        ...,
        description="URL of the single hero photo all batch images are edited from",
    )
    bio: Optional[str] = Field(
        default=None,
        max_length=4000,
        description="Free-text persona/profession narrative (stored as the character's context)",
    )
    name: Optional[str] = Field(
        default=None,
        max_length=50,
        description="Display name; defaults to persona.name when omitted",
    )

    @field_validator("hero_image_url")
    @classmethod
    def validate_hero_image_url(cls, v):
        # Fail fast at character-create time so every later batch build is safe (SSRF allowlist).
        try:
            return validate_source_image(v)
        except SourceImageError as e:
            raise ValueError(str(e))

    class Config:
        json_schema_extra = {
            "example": {
                "persona": {
                    "style": "realistic",
                    "ethnicity": "caucasian",
                    "age": 28,
                    "hairStyle": "straight",
                    "hairColor": "blonde",
                    "eyeColor": "green",
                    "bodyType": "curvy",
                    "breastSize": "medium",
                    "name": "Estella",
                    "personality": "temptress",
                    "occupation": "nurse",
                    "relationship": "girlfriend",
                    "kinks": ["playful_teasing", "slow_sensual"],
                },
                "hero_image_url": "https://xxx.supabase.co/storage/v1/object/public/images/estella.png",
                "bio": "A night-shift nurse; introverted, loves slow mornings.",
            }
        }


class CharacterUpdate(BaseModel):
    """Request body for PATCH /v1/characters/{id} — all fields optional."""

    persona: Optional[PersonaOptions] = None
    hero_image_url: Optional[str] = None
    bio: Optional[str] = Field(default=None, max_length=4000)
    name: Optional[str] = Field(default=None, max_length=50)

    @field_validator("hero_image_url")
    @classmethod
    def validate_hero_image_url(cls, v):
        if v is None:
            return v
        try:
            return validate_source_image(v)
        except SourceImageError as e:
            raise ValueError(str(e))


class CharacterRead(BaseModel):
    """Response body describing a character row."""

    id: str
    name: str
    persona: PersonaOptions
    hero_image_url: str
    bio: Optional[str] = None
    status: str = "draft"
    created_at: datetime
    updated_at: datetime
