"""
Pydantic models for Characters (Batch generation feature).

A Character is a real row in the product `characters` table (the one the chat
app reads): a persona stored in flat typed columns, attached to a single "hero"
photo (profile/avatar/chat_avatar URLs). Batches are generated by editing that
hero photo, so identity stays consistent across the whole set.

Characters are created with status='draft'; the admin publishes them from the
existing admin UI once the generated photos look right.
"""
from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field, field_validator

from services.url_guard import validate_source_image, SourceImageError

from .persona import PersonaEnrichment, PersonaField
from .requests import PersonaOptions


class CharacterCreate(BaseModel):
    """Request body for POST /v1/characters."""

    persona: PersonaOptions = Field(..., description="Character persona (identity + traits)")
    hero_image_url: str = Field(
        ...,
        description="URL of the single hero photo all batch images are edited from",
    )
    bio: Optional[str] = Field(
        default=None,
        max_length=4000,
        description="Free-text persona/profession narrative (stored as the character's context)",
    )
    name: Optional[str] = Field(
        default=None,
        max_length=50,
        description="Display name; defaults to persona.name when omitted",
    )
    generate_persona: bool = Field(
        default=False,
        description=(
            "If true, immediately generate + persist the character's free-text chat "
            "persona (system_prompt, greeting_message, etc.) via Venice right after "
            "creation, in this same call. Default off — fully back-compatible."
        ),
    )
    persona_fields: Optional[List[PersonaField]] = Field(
        default=None,
        description=(
            "Which persona fields to generate when generate_persona=true. None "
            "(default) = all generatable fields (system_prompt, greeting_message, "
            "tone, style, boundaries, summary, welcome_message, bio) EXCEPT: 'name' "
            "(already set by persona.name) and 'bio' when this request's own `bio` "
            "field is non-empty (a bio you typed here is never silently overwritten "
            "by generation — to regenerate it too, include \"bio\" explicitly). "
            "Ignored when generate_persona=false."
        ),
    )
    persona_enrichment: Optional[PersonaEnrichment] = Field(
        default=None,
        description=(
            "Optional transient likes/dislikes/interests/hobbies/language to flavor "
            "generation (not stored). Ignored when generate_persona=false."
        ),
    )
    persona_model_id: Optional[str] = Field(
        default=None,
        max_length=80,
        description=(
            "Optional model_id to record on the created chat_persona row. Ignored "
            "when generate_persona=false."
        ),
    )
    generate_traits: bool = Field(
        default=True,
        description=(
            "If true (default), immediately generate + persist the character's durable "
            "trait profile (wardrobe styles, demeanor, home taste, likes/dislikes, "
            "zodiac, ...) via the trait writer right after creation, in this same call. "
            "Best-effort: a failure never fails creation. Also covers /characters/bulk."
        ),
    )
    generate_nude_base: bool = Field(
        default=True,
        description=(
            "If true (default), immediately submit the character's identity-locked nude "
            "base render (the same text-to-image + ReActor face-lock path as POST "
            "/v1/characters/{id}/nude-base) right after creation, in this same call. Only "
            "fires when the nude-base services are configured AND settings.NUDE_BASE_T2I "
            "is on. Best-effort: a failure never fails creation. Also covers "
            "/characters/bulk. Set false to skip the auto-render for this character."
        ),
    )

    @field_validator("hero_image_url")
    @classmethod
    def validate_hero_image_url(cls, v):
        # Fail fast at character-create time so every later batch build is safe (SSRF allowlist).
        try:
            return validate_source_image(v)
        except SourceImageError as e:
            raise ValueError(str(e))

    class Config:
        json_schema_extra = {
            "example": {
                "persona": {
                    "style": "realistic",
                    "ethnicity": "caucasian",
                    "age": 28,
                    "hairStyle": "straight",
                    "hairColor": "blonde",
                    "eyeColor": "green",
                    "bodyType": "curvy",
                    "breastSize": "medium",
                    "name": "Estella",
                    "personality": "temptress",
                    "occupation": "nurse",
                    "relationship": "girlfriend",
                    "kinks": ["playful_teasing", "slow_sensual"],
                },
                "hero_image_url": "https://xxx.supabase.co/storage/v1/object/public/images/estella.png",
                "bio": "A night-shift nurse; introverted, loves slow mornings.",
                "generate_persona": True,
            }
        }


class CharacterUpdate(BaseModel):
    """Request body for PATCH /v1/characters/{id} — all fields optional."""

    persona: Optional[PersonaOptions] = None
    hero_image_url: Optional[str] = None
    bio: Optional[str] = Field(default=None, max_length=4000)
    name: Optional[str] = Field(default=None, max_length=50)

    @field_validator("hero_image_url")
    @classmethod
    def validate_hero_image_url(cls, v):
        if v is None:
            return v
        try:
            return validate_source_image(v)
        except SourceImageError as e:
            raise ValueError(str(e))


class CharacterRead(BaseModel):
    """Response body describing a character row."""

    id: str
    name: str
    persona: PersonaOptions
    hero_image_url: str
    bio: Optional[str] = None
    chat_persona_id: Optional[str] = None
    status: str = "draft"
    created_at: datetime
    updated_at: datetime


class BulkCharacterCreate(BaseModel):
    """Request body for POST /v1/characters/bulk (admin-only, Batch Character Creation).

    A list of characters to save, where each item is the exact `CharacterCreate` body
    the single `POST /v1/characters` uses (reused verbatim). Items succeed/fail
    INDEPENDENTLY — a bad item does not roll back the good ones.
    """

    items: List[CharacterCreate] = Field(
        ..., description="Characters to save; each is a full CharacterCreate body."
    )


class BulkCharacterError(BaseModel):
    """Per-item failure detail in a bulk-save response."""

    code: str = Field(..., description="Machine error code, e.g. CREATE_ERROR")
    message: str = Field(..., description="Human-readable failure reason")


class BulkCharacterItemResult(BaseModel):
    """One item's outcome in a POST /v1/characters/bulk response, in request order."""

    index: int = Field(..., description="0-based position of this item in the request")
    status: str = Field(..., description="'created' or 'failed'")
    character: Optional[CharacterRead] = Field(
        default=None, description="The created character (present when status == 'created')"
    )
    error: Optional[BulkCharacterError] = Field(
        default=None, description="Failure detail (present when status == 'failed')"
    )


class BulkCharacterResponse(BaseModel):
    """Response for POST /v1/characters/bulk (200 OK), per-item outcome in request order."""

    results: List[BulkCharacterItemResult] = Field(
        ..., description="One entry per input item, in request order"
    )
